[build]
  command = "yarn run build"
  publish = "dist"

[build.environment]
  HUGO_VERSION = "0.25.1"

[context.production.environment]
  HUGO_VERSION = "0.25.1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.25.1"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.25.1"
